#intem A
print (type(2.7))
#item B
print (type(27))
#intem C
print (type(False))
#item D
print (type("False"))
#item E
print (type("0.0"))
#item F
print (type(-21))
#item G
print (type(99999999))
#item h
print (type("None"))
#intem I
print (type(None))